
buildscript {
  ext {
    besuIdentifier = "linea-besu-${besuVersion}"
    besuFilename = "${besuIdentifier}.tar.gz"
    besuUrl = "${distributionBaseUrl}${besuVersion}/${besuFilename}"
    besuPluginsIdentifier = "${distributionIdentifier}-${version}"
    besuPluginDir = File.createTempDir("plugins")
  }
}

plugins {
  id 'java-library'
  id "org.sonarqube" version "4.3.1.3277"
}

sonar {
  properties {
    property "sonar.projectKey", "linea-tracer"
    property "sonar.organization", "myOrganization"
    property "sonar.host.url", "localhost:80"
    property "sonar.login", "admin"
    property "sonar.password", "Adminadmin123*"
    property "sonar.coverage.exclusions", "reference-tests/**/*, testing/**/*, **/*/Trace.java"
    property "sonar.coverage.jacoco.xmlReportPaths",
          // "${project.projectDir}/arithmetization/build/reports/jacoco/test/jacocoTestReport.xml"
          "${project.projectDir}/reference-tests/build/reports/jacoco/jacocoReferenceBlockchainTestsReport/jacocoReferenceBlockchainTestsReport.xml"
  }
}

version = project.hasProperty('releaseVersion') ? project.getProperty('releaseVersion') : 'snapshot'
