/*
 * Copyright ConsenSys AG.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package net.consensys.linea.zktracer.opcode;

import java.util.HashMap;
import java.util.Map;

import net.consensys.linea.zktracer.opcode.gas.Billing;
import net.consensys.linea.zktracer.opcode.gas.Gas;
import net.consensys.linea.zktracer.opcode.gas.MxpType;
import net.consensys.linea.zktracer.opcode.stack.Pattern;
import net.consensys.linea.zktracer.opcode.stack.StackSettings;

/** Contains information pertaining to each opcode that are required by the arithmetization. */
public enum OpCode {
  STOP(
      0x00,
      InstructionFamily.HALT,
      new StackSettings(
          Pattern.ZERO_ZERO,
          0,
          0,
          0,
          0,
          Gas.G_ZERO,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false),
      new RamSettings(),
      new Billing()),
  ADD(
      0x01,
      InstructionFamily.ADD,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  MUL(
      0x02,
      InstructionFamily.MUL,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SUB(
      0x03,
      InstructionFamily.ADD,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DIV(
      0x04,
      InstructionFamily.MUL,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SDIV(
      0x05,
      InstructionFamily.MOD,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  MOD(
      0x06,
      InstructionFamily.MOD,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SMOD(
      0x07,
      InstructionFamily.MOD,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  ADDMOD(
      0x8,
      InstructionFamily.EXT,
      new StackSettings(
          Pattern.THREE_ONE,
          1,
          3,
          1,
          3,
          Gas.G_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  MULMOD(
      0x9,
      InstructionFamily.EXT,
      new StackSettings(
          Pattern.THREE_ONE,
          1,
          3,
          1,
          3,
          Gas.G_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  EXP(
      0xa,
      InstructionFamily.MUL,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_EXP,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SIGNEXTEND(
      0xb,
      InstructionFamily.BIN,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  LT(
      0x10,
      InstructionFamily.WCP,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  GT(
      0x11,
      InstructionFamily.WCP,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SLT(
      0x12,
      InstructionFamily.WCP,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SGT(
      0x13,
      InstructionFamily.WCP,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  EQ(
      0x14,
      InstructionFamily.WCP,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  ISZERO(
      0x15,
      InstructionFamily.WCP,
      new StackSettings(
          Pattern.ONE_ONE,
          1,
          1,
          1,
          1,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  AND(
      0x16,
      InstructionFamily.BIN,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  OR(
      0x17,
      InstructionFamily.BIN,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  XOR(
      0x18,
      InstructionFamily.BIN,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  NOT(
      0x19,
      InstructionFamily.BIN,
      new StackSettings(
          Pattern.ONE_ONE,
          1,
          1,
          1,
          1,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  BYTE(
      0x1a,
      InstructionFamily.BIN,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SHL(
      0x1b,
      InstructionFamily.SHF,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SHR(
      0x1c,
      InstructionFamily.SHF,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SAR(
      0x1d,
      InstructionFamily.SHF,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),

  SHA3(
      0x20,
      InstructionFamily.KEC,
      new StackSettings(
          Pattern.TWO_ONE,
          1,
          2,
          1,
          2,
          Gas.S_MXP, // actual gas computed in MXP module
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(), // TODO
      Billing.byWord(MxpType.TYPE_4, Gas.G_KECCAK_256_WORD)),
  ADDRESS(
      0x30,
      InstructionFamily.CONTEXT,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BASE,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  BALANCE(
      0x31,
      InstructionFamily.ACCOUNT,
      new StackSettings(
          Pattern.ONE_ONE,
          1,
          1,
          1,
          1,
          Gas.S_HUB, // TODO: should be set to zero ... the real value is set in the
          // arithmetization (depends on warmth ...)
          false,
          false,
          true,
          false,
          false,
          false,
          false,
          true),
      new RamSettings(),
      new Billing()),
  ORIGIN(
      0x32,
      InstructionFamily.TRANSACTION,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BASE,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  CALLER(
      0x33,
      InstructionFamily.CONTEXT,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BASE,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false),
      new RamSettings(),
      new Billing()),
  CALLVALUE(
      0x34,
      InstructionFamily.CONTEXT,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BASE,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  CALLDATALOAD(
      0x35,
      InstructionFamily.STACK_RAM,
      new StackSettings(
          Pattern.LOAD_STORE,
          1,
          1,
          1,
          1,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          true,
          false,
          true,
          false,
          false),
      new RamSettings(),
      new Billing()),
  CALLDATASIZE(
      0x36,
      InstructionFamily.CONTEXT,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BASE,
          false,
          false,
          false,
          false,
          true,
          false,
          true,
          false),
      new RamSettings(),
      new Billing()),
  CALLDATACOPY(
      0x37,
      InstructionFamily.COPY,
      new StackSettings(
          Pattern.COPY,
          0,
          3,
          0,
          3,
          Gas.S_MXP,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(), // TODO
      Billing.byWord(MxpType.TYPE_4, Gas.G_COPY)),
  CODESIZE(
      0x38,
      InstructionFamily.ACCOUNT,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BASE,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  CODECOPY(
      0x39,
      InstructionFamily.COPY,
      new StackSettings(
          Pattern.COPY,
          0,
          3,
          0,
          3,
          Gas.S_MXP,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(), // TODO
      Billing.byWord(MxpType.TYPE_4, Gas.G_COPY)),
  GASPRICE(
      0x3a,
      InstructionFamily.TRANSACTION,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BASE,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  EXTCODESIZE(
      0x3b,
      InstructionFamily.ACCOUNT,
      new StackSettings(
          Pattern.ONE_ONE,
          1,
          1,
          1,
          1,
          Gas.S_HUB, // TODO: should be set to zero ... the real value is set in the arithmetization
          // (depends on warmth ...)
          false,
          false,
          true,
          false,
          false,
          false,
          true,
          false),
      new RamSettings(),
      new Billing()),
  EXTCODECOPY(
      0x3c,
      InstructionFamily.COPY,
      new StackSettings(
          Pattern.COPY, 0, 4, 0, 4, Gas.S_MXP, false, false, true, false, true, true, false, false),
      new RamSettings(), // TODO
      Billing.byWord(MxpType.TYPE_4, Gas.G_COPY)),
  RETURNDATASIZE(
      0x3d,
      InstructionFamily.CONTEXT,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BASE,
          false,
          false,
          false,
          false,
          true,
          true,
          false,
          false),
      new RamSettings(),
      new Billing()),
  RETURNDATACOPY(
      0x3e,
      InstructionFamily.COPY,
      new StackSettings(
          Pattern.COPY,
          0,
          3,
          0,
          3,
          Gas.S_MXP,
          false,
          false,
          false,
          false,
          false,
          true,
          true,
          false),
      new RamSettings(), // TODO
      Billing.byWord(MxpType.TYPE_4, Gas.G_COPY)),
  EXTCODEHASH(
      0x3f,
      InstructionFamily.ACCOUNT,
      new StackSettings(
          Pattern.ONE_ONE,
          1,
          1,
          1,
          1,
          Gas.S_HUB, // TODO: should be zero: it's all dynamic i.e. depends on account warmth
          false,
          false,
          true,
          false,
          false,
          true,
          false,
          false),
      new RamSettings(),
      new Billing()),
  BLOCKHASH(
      0x40,
      InstructionFamily.BATCH,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BLOCK_HASH,
          false,
          false,
          false, // TODO: do we want to raise it, if we keep this flag ?
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  COINBASE(
      0x41,
      InstructionFamily.BATCH,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BLOCK_HASH,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  TIMESTAMP(
      0x42,
      InstructionFamily.BATCH,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BLOCK_HASH,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  NUMBER(
      0x43,
      InstructionFamily.BATCH,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BLOCK_HASH,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DIFFICULTY(
      0x44,
      InstructionFamily.BATCH,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BLOCK_HASH,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  GASLIMIT(
      0x45,
      InstructionFamily.BATCH,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BLOCK_HASH,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  CHAINID(
      0x46,
      InstructionFamily.BATCH,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BLOCK_HASH,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SELFBALANCE(
      0x47,
      InstructionFamily.ACCOUNT,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_LOW,
          false,
          false,
          false,
          false,
          true,
          true,
          false,
          false),
      new RamSettings(),
      new Billing()),
  BASEFEE(
      0x48,
      InstructionFamily.BATCH,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BLOCK_HASH,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  POP(
      0x50,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ONE_ZERO,
          0,
          1,
          0,
          1,
          Gas.G_BASE,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  MLOAD(
      0x51,
      InstructionFamily.STACK_RAM,
      new StackSettings(
          Pattern.ONE_ONE,
          1,
          1,
          1,
          1,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(), // TODO
      Billing.byMxp(MxpType.TYPE_2)),
  MSTORE(
      0x52,
      InstructionFamily.STACK_RAM,
      new StackSettings(
          Pattern.TWO_ZERO,
          0,
          2,
          0,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      Billing.byMxp(MxpType.TYPE_2)),
  MSTORE8(
      0x53,
      InstructionFamily.STACK_RAM,
      new StackSettings(
          Pattern.TWO_ZERO,
          0,
          2,
          0,
          2,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(), // TODO
      Billing.byMxp(MxpType.TYPE_3)),
  SLOAD(
      0x54,
      InstructionFamily.STORAGE,
      new StackSettings(
          Pattern.ONE_ONE,
          1,
          1,
          1,
          1,
          Gas.S_HUB, // complex computation done in the hub
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SSTORE(
      0x55,
      InstructionFamily.STORAGE,
      new StackSettings(
          Pattern.ONE_ONE,
          0,
          2,
          0,
          2,
          Gas.S_HUB, // complex computation done in the hub
          false,
          true,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  JUMP(
      0x56,
      InstructionFamily.JUMP,
      new StackSettings(
          Pattern.ONE_ZERO,
          0,
          2,
          0,
          2,
          Gas.G_MID,
          false,
          false,
          false,
          true,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  JUMPI(
      0x57,
      InstructionFamily.JUMP,
      new StackSettings(
          Pattern.ONE_ZERO,
          0,
          1,
          0,
          1,
          Gas.G_MID,
          false,
          false,
          false,
          true,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PC(
      0x58,
      InstructionFamily.MACHINE_STATE,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BASE,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  MSIZE(
      0x59,
      InstructionFamily.MACHINE_STATE,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BASE,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false),
      new RamSettings(),
      Billing.byMxp(MxpType.TYPE_1)), // TODO
  GAS(
      0x5a,
      InstructionFamily.MACHINE_STATE,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_BASE,
          false,
          false,
          false,
          false,
          false,
          false,
          true,
          false),
      new RamSettings(),
      new Billing()),
  JUMPDEST(
      0x5b,
      InstructionFamily.MACHINE_STATE,
      new StackSettings(
          Pattern.ZERO_ZERO,
          0,
          0,
          0,
          0,
          Gas.G_JUMP_DEST,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          true),
      new RamSettings(),
      new Billing()),
  // PUSH0(
  // 0x5f,
  // memoryFlags,
  // moduleFlags,
  // ramSettings,
  // ramFlag,
  // ),
  PUSH1(
      0x60,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH2(
      0x61,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH3(
      0x62,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH4(
      0x63,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH5(
      0x64,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH6(
      0x65,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH7(
      0x66,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH8(
      0x67,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH9(
      0x68,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH10(
      0x69,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH11(
      0x6a,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH12(
      0x6b,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH13(
      0x6c,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH14(
      0x6d,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH15(
      0x6e,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH16(
      0x6f,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH17(
      0x70,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH18(
      0x71,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH19(
      0x72,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH20(
      0x73,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH21(
      0x74,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH22(
      0x75,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH23(
      0x76,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH24(
      0x77,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH25(
      0x78,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH26(
      0x79,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH27(
      0x7a,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH28(
      0x7b,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH29(
      0x7c,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH30(
      0x7d,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH31(
      0x7e,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  PUSH32(
      0x7f,
      InstructionFamily.PUSH_POP,
      new StackSettings(
          Pattern.ZERO_ONE,
          1,
          0,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP1(
      0x80,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          2,
          1,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP2(
      0x81,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          3,
          2,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP3(
      0x82,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          4,
          3,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP4(
      0x83,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          5,
          4,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP5(
      0x84,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          6,
          5,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP6(
      0x85,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          7,
          6,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP7(
      0x86,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          8,
          7,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP8(
      0x87,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          9,
          8,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP9(
      0x88,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          10,
          9,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP10(
      0x89,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          11,
          10,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP11(
      0x8a,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          12,
          11,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP12(
      0x8b,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          13,
          12,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP13(
      0x8c,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          14,
          13,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP14(
      0x8d,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          15,
          14,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP15(
      0x8e,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          16,
          15,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  DUP16(
      0x8f,
      InstructionFamily.DUP,
      new StackSettings(
          Pattern.DUP,
          17,
          16,
          1,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP1(
      0x90,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          2,
          2,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP2(
      0x91,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          3,
          3,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP3(
      0x92,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          4,
          4,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP4(
      0x93,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          5,
          5,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP5(
      0x94,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          6,
          6,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP6(
      0x95,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          7,
          7,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP7(
      0x96,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          8,
          8,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP8(
      0x97,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          9,
          9,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP9(
      0x98,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          10,
          10,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP10(
      0x99,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          11,
          11,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP11(
      0x9a,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          12,
          12,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP12(
      0x9b,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          13,
          13,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP13(
      0x9c,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          14,
          14,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP14(
      0x9d,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          15,
          15,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP15(
      0x9e,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          16,
          16,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SWAP16(
      0x9f,
      InstructionFamily.SWAP,
      new StackSettings(
          Pattern.SWAP,
          17,
          17,
          0,
          0,
          Gas.G_VERY_LOW,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  LOG0(
      0xa0,
      InstructionFamily.LOG,
      new StackSettings(
          Pattern.LOG,
          0,
          2,
          0,
          2,
          Gas.G_LOG_0,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(), // TODO
      Billing.byByte(MxpType.TYPE_4, Gas.G_LOG_DATA)),
  LOG1(
      0xa1,
      InstructionFamily.LOG,
      new StackSettings(
          Pattern.LOG,
          0,
          3,
          0,
          3,
          Gas.G_LOG_1,
          true,
          true,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(), // TODO
      Billing.byByte(MxpType.TYPE_4, Gas.G_LOG_DATA)),
  LOG2(
      0xa2,
      InstructionFamily.LOG,
      new StackSettings(
          Pattern.LOG, 0, 4, 0, 4, Gas.G_LOG_2, true, true, false, false, true, false, true, false),
      new RamSettings(), // TODO
      Billing.byByte(MxpType.TYPE_4, Gas.G_LOG_DATA)),
  LOG3(
      0xa3,
      InstructionFamily.LOG,
      new StackSettings(
          Pattern.LOG, 0, 5, 0, 5, Gas.G_LOG_3, true, true, false, false, true, true, false, false),
      new RamSettings(), // TODO
      Billing.byByte(MxpType.TYPE_4, Gas.G_LOG_DATA)),
  LOG4(
      0xa4,
      InstructionFamily.LOG,
      new StackSettings(
          Pattern.LOG, 0, 6, 0, 6, Gas.G_LOG_4, true, true, false, false, true, true, true, false),
      new RamSettings(), // TODO
      Billing.byByte(MxpType.TYPE_4, Gas.G_LOG_DATA)),
  CREATE(
      0xf0,
      InstructionFamily.CREATE,
      new StackSettings(
          Pattern.CREATE,
          1,
          3,
          1,
          3,
          Gas.G_CREATE,
          true,
          true,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(), // TODO
      Billing.byMxp(MxpType.TYPE_4)),
  CALL(
      0xf1,
      InstructionFamily.CALL,
      new StackSettings(
          Pattern.CALL,
          1,
          7,
          1,
          7,
          Gas.S_CALL, // TODO: computed in STP module
          true,
          true,
          true,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(),
      Billing.byMxp(MxpType.TYPE_5)),
  CALLCODE(
      0xf2,
      InstructionFamily.CALL,
      new StackSettings(
          Pattern.CALL,
          1,
          7,
          1,
          7,
          Gas.S_CALL, // TODO: computed in STP module
          true,
          false,
          true,
          false,
          false,
          true,
          false,
          false),
      new RamSettings(), // TODO
      Billing.byMxp(MxpType.TYPE_5)),
  RETURN(
      0xf3,
      InstructionFamily.HALT,
      new StackSettings(
          Pattern.TWO_ZERO,
          0,
          2,
          0,
          2,
          Gas.S_MXP,
          false,
          false,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(), // TODO
      Billing.byMxp(MxpType.TYPE_4)),
  DELEGATECALL(
      0xf4,
      InstructionFamily.CALL,
      new StackSettings(
          Pattern.CALL,
          1,
          7,
          1,
          7,
          Gas.S_CALL, // TODO: computed in STP module
          true,
          false,
          true,
          false,
          false,
          false,
          true,
          false),
      new RamSettings(), // TODO
      Billing.byMxp(MxpType.TYPE_5)),
  CREATE2(
      0xf5,
      InstructionFamily.CREATE,
      new StackSettings(
          Pattern.CREATE,
          1,
          4,
          1,
          4,
          Gas.G_CREATE,
          true,
          true,
          false,
          false,
          true,
          false,
          false,
          false),
      new RamSettings(), // TODO
      Billing.byWord(MxpType.TYPE_4, Gas.G_KECCAK_256_WORD)),
  STATICCALL(
      0xfa,
      InstructionFamily.CALL,
      new StackSettings(
          Pattern.CALL,
          1,
          6,
          1,
          6,
          Gas.S_CALL, // TODO: computed in STP module
          true,
          false,
          true,
          false,
          false,
          false,
          false,
          true),
      new RamSettings(), // TODO
      Billing.byMxp(MxpType.TYPE_5)),
  REVERT(
      0xfd,
      InstructionFamily.HALT,
      new StackSettings(
          Pattern.TWO_ZERO,
          0,
          2,
          0,
          2,
          Gas.S_MXP,
          false,
          false,
          false,
          false,
          false,
          true,
          false,
          false),
      new RamSettings(), // TODO
      Billing.byMxp(MxpType.TYPE_4)),
  INVALID(
      0xfe,
      InstructionFamily.INVALID,
      new StackSettings(
          Pattern.ZERO_ZERO,
          0,
          0,
          0,
          0,
          Gas.G_ZERO,
          false,
          false,
          false,
          false,
          false,
          false,
          false,
          false),
      new RamSettings(),
      new Billing()),
  SELFDESTRUCT(
      0xff,
      InstructionFamily.HALT,
      new StackSettings(
          Pattern.TWO_ZERO,
          0,
          1,
          0,
          1,
          Gas.S_MXP,
          false,
          true,
          true,
          false,
          false,
          false,
          false,
          true),
      new RamSettings(), // TODO
      new Billing()); // TODO

  /** A long -> OpCode mapping from opcode value to {@link OpCode} instances. */
  private static final Map<Long, OpCode> BY_VALUE = new HashMap<>(values().length);

  /** The actual unsigned byte value of the opcode. */
  public final long value;
  /** The {@link InstructionFamily} to which the opcode belongs. */
  public final InstructionFamily family;
  /** A {@link StackSettings} instance describing how the opcode alters the EVM stack. */
  public final StackSettings stackSettings;
  /** A {@link RamSettings} instance describing how the opcode alters the memory. */
  public final RamSettings ramSettings;
  /** A {@link Billing} instance describing the billing scheme of the instruction. */
  public final Billing billing;

  static {
    for (OpCode o : values()) {
      BY_VALUE.put(o.value, o);
    }
  }

  OpCode(
      final int value,
      InstructionFamily family,
      StackSettings stackSettings,
      RamSettings ramSettings,
      Billing billing) {
    this.value = value;
    this.family = family;
    this.stackSettings = stackSettings;
    this.ramSettings = ramSettings;
    this.billing = billing;
  }

  /**
   * A method singling out <code>PUSHx</code> instructions.
   *
   * @return <code>true</code> if this opcode is a <code>PUSHx</code>
   */
  boolean isPush() {
    return (0x60 <= this.value) && (this.value < 0x80);
  }

  /**
   * Converts a numeric value to an Opcode. Throws if the value is not an unsigned byte.
   *
   * @param code
   * @return the corresponding {@link OpCode}
   */
  public static OpCode of(final long code) {
    if (code < 0 || code > 255) {
      throw new AssertionError("No OpCode with value " + code + " is defined.");
    }
    return BY_VALUE.getOrDefault(code, OpCode.INVALID);
  }

  public int numberOfArguments() {
    return this.stackSettings.nbRemoved();
  }
}
