name: "Validate Gradle Wrapper"
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - '**'
jobs:
  validation:
    if: github.event.pull_request.draft == false && github.base_ref != 'main'
    name: "Validation"
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-med
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
