name: Weekly Precompile Call Tests

on:
  pull_request:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  weekly-prc-call-tests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Test Environment
        uses: ./.github/actions/setup-environment

      - name: Run Precompile Call tests
        run: GOMAXPROCS=1 GOMEMLIMIT=5GiB ./gradlew prcCallTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          PRC_CALL_TESTS_PARALLELISM: 24
          GOCORSET_FLAGS: -vw -b1024 --ansi-escapes=false --report --hir

      - name: Upload prc calls test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: prc-call-tests-report
          path: arithmetization/build/reports/tests/**/*

      - name: Failure Notification
        if: ${{ failure() || cancelled() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            name: "Precompile call"
            status: "${{ job.status }}"
