permissions: read-all
name: "Unit & Fast Replay Tests"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      tests-with-ssh:
        description: Run tests with ability to ssh into environment
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ==================================================================
  # Build
  # ==================================================================
  build:
    if: github.event.pull_request.draft == false && github.base_ref != 'main'
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-med
    steps:

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: false

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@eaa888eb19115a521fa72b65cd94fe1f25bbcaac #v1.3

      - name: Build without tests
        run: ./gradlew build -x test -x spotlessCheck
        env:
          JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false

      - name: Store distribution artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: distributions
          path: arithmetization/build/libs

      - name: Run spotless
        run: ./gradlew --no-daemon --parallel clean spotlessCheck

  # ==================================================================
  # Unit Tests
  # ==================================================================
  unit-tests-prague:
    needs: [ build ]
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      zkevm_fork: PRAGUE
      tests-with-ssh: ${{ inputs.tests-with-ssh || false}}

  # ==================================================================
  # Fast Replay Tests
  # ==================================================================
  replay-tests:
    if: github.event.pull_request.draft == false && github.base_ref != 'main'
    needs: [ build ]
    uses: ./.github/workflows/reusable-fast-replay-tests.yml
    with:
      tests-with-ssh: ${{ inputs.tests-with-ssh || false}}
