name: "Fast Replay Tests"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      tests-with-ssh:
        description: Run tests with ability to ssh into environment
        required: false
        type: boolean
        default: false


env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  run-tests:
    uses: ./gradle-template-tests.yml
    with:
      environment: 'testname'
      tag: fastReplayTests
